### ISSUE TITLE
dva-engine is not visualizer

### ISSUE THREAD

**Issue by hmmhmmhm** [sylingd/ow-workshop#14]
Hello, I've seen the documents of this, thanks for introducing of my dva-engine, but in the documents are wrong classification the dva-engine to visualizer tools(可视化工具) categories. i think it might be correct categories is the 解释器.

**Comment by millionart** [comment]
This part of the content was added by me.
At that time, the dva engine was also called overwatch-workshop-javascript. I remember that you have a plan to implement visual editing in your todo list, so I did this classification. Unfortunately, it seems that you canceled the development plan.

**Comment by sylingd** [comment]
Thank you, I will correct it later

**Comment by hmmhmmhm** [comment]
Actually, I didn't give up on that feature, but I just haven't been able to work because I've had so much other work to do lately. Okay, the dva engine will have a lot of extra features. Decompiler, visual scripting, community web (it'll be like a dva-styler), plug-in system.... i'll be soon make it!,,,
